/**
 * 一键成书系统常量定义
 */

/**
 * 提示词组阶段类型常量（对应后端）
 */
export const PROMPT_GROUP_STAGE_TYPES = {
  /** 脑洞生成提示词 */
  IDEA_GENERATION: 'idea_generation',
  
  /** 脑洞优化提示词 */
  IDEA_OPTIMIZE: 'idea_optimize',
  
  /** 书名简介生成提示词 */
  TITLE_GENERATION: 'title_generation',
  
  /** 主大纲生成提示词 */
  MAIN_OUTLINE_GENERATION: 'main_outline_generation',
  
  /** 大纲优化提示词 */
  MAIN_OUTLINE_OPTIMIZE: 'main_outline_optimize',
  
  /** 卷纲生成提示词 */
  VOLUME_OUTLINE_GENERATION: 'volume_outline_generation',
  
  /** 卷纲优化提示词 */
  VOLUME_OUTLINE_OPTIMIZE: 'volume_outline_optimize',
  
  /** 细纲生成提示词 */
  CHAPTER_OUTLINE_GENERATION: 'chapter_outline_generation',
  
  /** 细纲优化提示词 */
  CHAPTER_OUTLINE_OPTIMIZE: 'chapter_outline_optimize',
  
  /** 章节正文生成提示词 */
  CONTENT_GENERATION: 'content_generation',
  
  /** 章节审稿提示词 */
  REVIEW: 'review',
  
  /** 章节梗概生成提示词 */
  SUMMARY_GENERATION: 'summary_generation',
} as const;

/**
 * 阶段类型对应的显示标签
 */
export const STAGE_TYPE_LABELS: Record<string, string> = {
  [PROMPT_GROUP_STAGE_TYPES.IDEA_GENERATION]: '脑洞生成',
  [PROMPT_GROUP_STAGE_TYPES.IDEA_OPTIMIZE]: '脑洞优化',
  [PROMPT_GROUP_STAGE_TYPES.TITLE_GENERATION]: '书名简介生成',
  [PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_GENERATION]: '主大纲生成',
  [PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_OPTIMIZE]: '大纲优化',
  [PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_GENERATION]: '卷纲生成',
  [PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_OPTIMIZE]: '卷纲优化',
  [PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_GENERATION]: '细纲生成',
  [PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_OPTIMIZE]: '细纲优化',
  [PROMPT_GROUP_STAGE_TYPES.CONTENT_GENERATION]: '章节正文生成',
  [PROMPT_GROUP_STAGE_TYPES.REVIEW]: '章节审稿',
  [PROMPT_GROUP_STAGE_TYPES.SUMMARY_GENERATION]: '章节梗概生成',
};

/**
 * 必需的阶段类型（不可跳过）
 */
export const REQUIRED_STAGE_TYPES = [
  PROMPT_GROUP_STAGE_TYPES.IDEA_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.TITLE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.CONTENT_GENERATION,
];

/**
 * 可选的阶段类型（可跳过）
 */
export const OPTIONAL_STAGE_TYPES = [
  PROMPT_GROUP_STAGE_TYPES.IDEA_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.REVIEW,
  PROMPT_GROUP_STAGE_TYPES.SUMMARY_GENERATION,
];

/**
 * 阶段类型与PromptConfig字段的映射
 */
export const STAGE_TYPE_TO_CONFIG_FIELD: Record<string, string> = {
  [PROMPT_GROUP_STAGE_TYPES.IDEA_GENERATION]: 'ideaPromptId',
  [PROMPT_GROUP_STAGE_TYPES.IDEA_OPTIMIZE]: 'ideaOptimizePromptId',
  [PROMPT_GROUP_STAGE_TYPES.TITLE_GENERATION]: 'titlePromptId',
  [PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_GENERATION]: 'mainOutlinePromptId',
  [PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_OPTIMIZE]: 'mainOutlineOptimizePromptId',
  [PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_GENERATION]: 'volumeOutlinePromptId',
  [PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_OPTIMIZE]: 'volumeOutlineOptimizePromptId',
  [PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_GENERATION]: 'chapterOutlinePromptId',
  [PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_OPTIMIZE]: 'chapterOutlineOptimizePromptId',
  [PROMPT_GROUP_STAGE_TYPES.CONTENT_GENERATION]: 'contentPromptId',
  [PROMPT_GROUP_STAGE_TYPES.REVIEW]: 'reviewPromptId',
  [PROMPT_GROUP_STAGE_TYPES.SUMMARY_GENERATION]: 'summaryPromptId',
};

/**
 * 所有阶段类型（按顺序）
 */
export const ALL_STAGE_TYPES = [
  PROMPT_GROUP_STAGE_TYPES.IDEA_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.IDEA_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.TITLE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.MAIN_OUTLINE_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.VOLUME_OUTLINE_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.CHAPTER_OUTLINE_OPTIMIZE,
  PROMPT_GROUP_STAGE_TYPES.CONTENT_GENERATION,
  PROMPT_GROUP_STAGE_TYPES.REVIEW,
  PROMPT_GROUP_STAGE_TYPES.SUMMARY_GENERATION,
];

